formal_login:
  url: "http://36.134.46.91:7070/"
  username: zhangyuanlong
  password: 123456



case_login:
  url: "http://192.168.110.210:9016/"
  username: zhangyuanlong
  password: 123456




add_bug: "false"
