formal_login:
  url: "https://cloud.yu-con.com/login?id=1115qi"
  cookies_url: "https://cloud.yu-con.com"
  username: root1
  password: 123456



test_login:
  url: "http://192.168.110.210:9016/"
  cookies_url: "http://192.168.110.210:9016/"
  username: zhangyuanlong
  password: 123456




formal_root_login:
  url: "https://cloud.yu-con.com"
  cookies_url: "https://cloud.yu-con.com"
  username: zhangyuanlong
  password: 123456



add_bug: "false"

asserts_switch: "true"

get_alert_switch: "true"
